### ISSUE TITLE
关于你来信中的“其中userManage一直都是null”的问题的回复

### ISSUE THREAD

**Issue by waylau** [ydcun/ssh_annotaction#1]
你来信（162<ydcun@163.com>）中描述

```java
@Component
@Path("test")
public class TestResource {
            @Autowired
            private IUserManage userManage;
 
            @Path("getText")
            @GET
            @Produces("text/plain")
            public String getText() {
                        return "hello lucky";
            }
………
```

userManage 为null ,说明是 Spring bean 初始化失败，
看你了你的 IUserManage  它是一个接口，且未用任何注解或者xml 形式将其 注入 Spring容器，故未实例化。

我觉得你这里的本意是想用   com/ydcun/service/UserManageImp.java

你将上面的这句改为  

```java
         @Autowired
            private UserManageImp  userManageImp;
```

试下

**Comment by waylau** [comment]
刚我再次审视了你的代码，提出以下几点，希望对你有用(因 gmail 经常抽风，故回复在此):

1. 你的项目中的 是 Spring 4，而我的 是  Spring 3 ,Jersey 与 Spring 集成 是需要另外的包“jersey-spring3”，详见 《Jersey 2.x 用户指南》 Chapter 22. Spring DI 使用 Spring 注入  https://github.com/waylau/Jersey-2.x-User-Guide  。而你的项目中并没有该包
e 
2. Jersey提供的集成包 jersey-spring3， 暂时只支持 Spring3的集成
3. 若需要继承 Spring 4,可以参阅 http://www.waylau.com/jersey-2-with-spring-4/ 
4. SpringMVC 与 Jersey 在 url 映射这层，功能上是有重叠的，两者选其一即可（SpringMVC 本身也是支持 REST）。

**Comment by ydcun** [comment]
谢谢你的回复，我查了下spring4 MVC 对RESTful的风格支持也不错。既然这样就决定直接用springMVC的RESTful了。应该也是出于这个的原因jersey-spring3一直都没有持续更新到支持4 
谢谢您耐心的解答。
